# Generated by Django 5.1.7 on 2025-04-25 15:49

import candidatures.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_candidature', models.CharField(choices=[('en attente', 'En attente'), ('accepté', 'Accepté'), ('refusé', 'Refusé')], default='en attente', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(blank=True, max_length=255, null=True, upload_to=candidatures.models.Candidature.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('lettre_motivation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('entreprise', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance'), ('Freelance', 'Freelance')], max_length=100)),
                ('categorie', models.CharField(choices=[('Tech', 'Tech'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('RH', 'Ressources Humaines'), ('Commercial', 'Commercial'), ('Autre', 'Autre')], max_length=100)),
                ('description', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='TableauBord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jour', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatures.candidature')),
            ],
        ),
        migrations.AddField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatures.offreemploi'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='recruteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='candidatures.profile'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='candidatures.profile'),
        ),
    ]
